services:
  hydra:
    image: oryd/hydra:v2.3.0
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
    command: serve -c /etc/config/hydra/hydra.yml all --dev
    volumes:
      - hydra-sqlite:/var/lib/sqlite:Z
      - ./docker/hydra:/etc/config/hydra:Z
    environment:
      DSN: "sqlite:///var/lib/sqlite/db.sqlite?_fk=true"
      URLS_SELF_ISSUER: "http://127.0.0.1:4444"
    restart: unless-stopped
    depends_on:
      - hydra-migrate
    networks:
      - hydra

  hydra-migrate:
    image: oryd/hydra:v2.3.0
    environment:
      DSN: "sqlite:///var/lib/sqlite/db.sqlite?_fk=true"
    command: migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      - hydra-sqlite:/var/lib/sqlite:Z
      - ./docker/hydra:/etc/config/hydra:Z
    restart: on-failure
    networks:
      - hydra

  # Adding a second hydra to act as a different OAuth2 provider
  hydra-2:
    image: oryd/hydra:v2.3.0
    ports:
      - "4454:4454" # Public port
      - "4455:4455" # Admin port
    command: serve -c /etc/config/hydra/hydra.yml all --dev
    volumes:
      - hydra-2-sqlite:/var/lib/sqlite:Z
      - ./docker/hydra:/etc/config/hydra:Z
    environment:
      DSN: "sqlite:///var/lib/sqlite/db.sqlite?_fk=true"
      URLS_SELF_ISSUER: "http://127.0.0.1:4454"
      SERVE_PUBLIC_PORT: "4454"
      SERVE_ADMIN_PORT: "4455"
    restart: unless-stopped
    depends_on:
      - hydra-2-migrate
    networks:
      - hydra-2

  hydra-2-migrate:
    image: oryd/hydra:v2.3.0
    environment:
      DSN: "sqlite:///var/lib/sqlite/db.sqlite?_fk=true"
    command: migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      - hydra-2-sqlite:/var/lib/sqlite:Z
      - ./docker/hydra:/etc/config/hydra:Z
    restart: on-failure
    networks:
      - hydra-2

networks:
  hydra:
  hydra-2:

volumes:
  hydra-sqlite:
  hydra-2-sqlite:
