services:
  hydra:
    image: oryd/hydra:v2.3.0
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
    command: serve -c /etc/config/hydra/hydra.yml all --dev
    volumes:
      - hydra-sqlite:/var/lib/sqlite:rw
      - ./docker/hydra:/etc/config/hydra:ro
    environment:
      DSN: "sqlite:///var/lib/sqlite/db.sqlite?_fk=true"
      URLS_SELF_ISSUER: "http://127.0.0.1:4444"
    restart: unless-stopped
    depends_on:
      - hydra-migrate
    networks:
      - hydra
    user: "0:0"

  hydra-migrate:
    image: oryd/hydra:v2.3.0
    environment:
      DSN: "sqlite:///var/lib/sqlite/db.sqlite?_fk=true"
    command: migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      - hydra-sqlite:/var/lib/sqlite:rw
      - ./docker/hydra:/etc/config/hydra:ro
    restart: on-failure
    networks:
      - hydra
    user: "0:0"

  hydra-init-clients:
    image: alpine/curl:latest
    entrypoint: ["/bin/sh"]
    command: ["/etc/hydra/init/create-test-clients.sh"]
    volumes:
      - ./docker/hydra/init:/etc/hydra/init:ro
    depends_on:
      - hydra
    networks:
      - hydra
    restart: on-failure

  # Adding a second hydra to act as a different OAuth2 provider
  hydra-2:
    image: oryd/hydra:v2.3.0
    ports:
      - "4454:4454" # Public port
      - "4455:4455" # Admin port
    command: serve -c /etc/config/hydra/hydra.yml all --dev
    volumes:
      - hydra-2-sqlite:/var/lib/sqlite:rw
      - ./docker/hydra:/etc/config/hydra:ro
    environment:
      DSN: "sqlite:///var/lib/sqlite/db2.sqlite?_fk=true"
      URLS_SELF_ISSUER: "http://127.0.0.1:4454"
      SERVE_PUBLIC_PORT: "4454"
      SERVE_ADMIN_PORT: "4455"
    restart: unless-stopped
    depends_on:
      - hydra-2-migrate
    networks:
      - hydra-2
    user: "0:0"

  hydra-2-migrate:
    image: oryd/hydra:v2.3.0
    environment:
      DSN: "sqlite:///var/lib/sqlite/db2.sqlite?_fk=true"
    command: migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      - hydra-2-sqlite:/var/lib/sqlite:rw
      - ./docker/hydra:/etc/config/hydra:ro
    restart: on-failure
    networks:
      - hydra-2
    user: "0:0"

  hydra-2-init-clients:
    image: alpine/curl:latest
    entrypoint: ["/bin/sh"]
    command: ["/etc/hydra/init/create-test-clients.sh"]
    volumes:
      - ./docker/hydra/init:/etc/hydra/init:ro
    depends_on:
      - hydra-2
    networks:
      - hydra-2
    environment:
      HYDRA_ADMIN_URL: "http://hydra-2:4455"
      HYDRA_PUBLIC_URL: "http://hydra-2:4454"
    restart: on-failure

networks:
  hydra:
  hydra-2:

volumes:
  hydra-sqlite:
  hydra-2-sqlite:
