[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"

[target.x86_64-unknown-linux-musl]
linker = "musl-gcc"

# Environment variables for all targets
[env]
# Disable BMI2 instructions which are x86_64 specific
CARGO_CFG_TARGET_FEATURE = { value = "", force = true }
