# Minimal Nexus configuration for Docker
# This configuration starts a basic Nexus service with MCP support

[server]
# Bind to all interfaces on port 3000 for container networking
listen_address = "0.0.0.0:3000"

[server.health]
# Enable health endpoint for container health checks
enabled = true
path = "/health"

# OAuth2 configuration (optional)
# Uncomment and configure to enable JWT authentication
# [server.oauth]
# url = "https://your-oauth-provider.com/.well-known/jwks.json"
# poll_interval = "5m"
# expected_issuer = "https://your-oauth-provider.com"
# expected_audience = "your-service-audience"
#
# [server.oauth.protected_resource]
# resource = "https://your-nexus-instance.com"
# authorization_servers = ["https://your-oauth-provider.com"]

[mcp]
# Enable Model Context Protocol support
enabled = true
# MCP endpoint will be available at /mcp
path = "/mcp"

[mcp.servers.github]
url = "https://api.githubcopilot.com/mcp/"
auth.token = "{{ env.GITHUB_TOKEN }}"

# No MCP servers are configured by default
# Users can add their own servers by extending this configuration
