[profile.ci]
# grafbase extension build test compile tons of stuff and thus a super slow.
slow-timeout = { period = "1m", terminate-after = 3 }
retries = 2
failure-output = "immediate-final"
fail-fast = false

[profile.ci.junit]
# output test results at target/nextest/ci/junit.xml
path = "junit.xml"
store-success-output = true
store-failure-output = true
