name: Tests

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  DEPOT_PROJECT: lc6t0h7bhh

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-rust-pr
  cancel-in-progress: true

jobs:
  check-format:
    runs-on: depot-ubuntu-24.04-small
    steps:
      - name: Get sources
        uses: actions/checkout@v4

      - name: Install Rust
        uses: ./.github/actions/install-rust
        with:
          components: rustfmt

      - name: cargo fmt
        shell: bash
        run: |
          cargo fmt --check

      - uses: uncenter/setup-taplo@4f203fdb4f3b1e289c8382cf90d8397d2338df2e # v1.0.8
        with:
          version: "0.9.3"

      - name: taplo fmt check
        shell: bash
        run: |
          taplo fmt --check
          taplo check

  tests:
    strategy:
      fail-fast: false
      matrix:
        platform:
          [
            {
              "target": "x86_64-unknown-linux-musl",
              "runner": "depot-ubuntu-24.04-8",
            },
            {
              "target": "aarch64-unknown-linux-musl",
              "runner": "depot-ubuntu-24.04-arm-8",
            },
            {
              "target": "aarch64-apple-darwin",
              "runner": "depot-macos-latest",
            },
            {
              "target": "x86_64-pc-windows-msvc",
              "runner": "depot-windows-2022-8",
            },
          ]
    runs-on: ${{ matrix.platform.runner }}
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - name: Get sources
        uses: actions/checkout@v4

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9

      - name: Install Rust
        uses: ./.github/actions/install-rust
        with:
          target: ${{ matrix.platform.target }}
          components: clippy, rustfmt

      - name: Install musl-tools
        if: ${{ contains(matrix.platform.target, 'linux') }}
        shell: bash
        run: |
          sudo apt-get install musl musl-tools
          # This seems like a horrible hack that might come back to bite, but lets see!
          sudo ln -s /bin/g++ /bin/musl-g++
          sudo ln -s /bin/g++ /bin/aarch64-linux-musl-g++

      - name: Install cargo-nextest
        uses: taiki-e/install-action@d12e869b89167df346dd0ff65da342d1fb1202fb # v2.53.2
        with:
          tool: nextest

      - if: runner.os == 'Windows'
        uses: ilammy/setup-nasm@72793074d3c8cdda771dba85f6deafe00623038b # v1

      - name: Clippy
        shell: bash
        run: |
          cargo clippy \
            --locked \
            --target ${{ matrix.platform.target }}

      - name: Tests
        id: tests
        shell: bash
        run: |
          cargo nextest run --target ${{ matrix.platform.target }} --no-tests=warn --profile ci

  after-build-rust:
    # This job is responsible for reacting to build success or failure. It must
    # happen after the builds, hence the `needs`. But it must not be skipped
    # when the builds are cancelled or fail (hence the `if: ${{ always() }}`).
    needs: [check-format, tests]
    runs-on: depot-ubuntu-24.04-small
    steps:
      - name: Check that the builds succeeded
        run: exit 1
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
